export const ITEM_STATUS = {
    REPORTED: 'REPORTED',
    MATCH_FOUND: 'MATCH_FOUND',
    CLAIM_REQUESTED: 'CLAIM_REQUESTED',
    VERIFIED: 'VERIFIED',
    RESOLVED: 'RESOLVED',
    SECURED: 'SECURED',
    REJECTED: 'REJECTED',
};
